import type { OnboardingTour } from "./types";

/**
 * Tutorial guiado del admin.
 * El host NO navega solo: los pasos con requirePath enseñan a abrir la pantalla
 * desde el menú y esperan a que el usuario lo haga.
 */
export const ADMIN_ONBOARDING: OnboardingTour = {
  id: "admin",
  title: "Tutorial del panel",
  subtitle: "Recorrido guiado por la operación diaria",
  welcomeTitle: "Te damos la bienvenida al panel Soundtec",
  welcomeBody:
    "Este tutorial te acompaña módulo por módulo: clientes, precios, catálogo, pedidos y cotizaciones. En cada paso te mostramos qué clickear; el salto entre pantallas lo hacés vos. Importante: es solo un paseo — no uses Guardar, Enviar, Emitir ni Crear. Si solo mirás y navegás, no se guarda nada.",
  steps: [
    {
      id: "admin-menu",
      route: "/admin",
      target: "nav-sidebar",
      title: "El menú es tu mapa",
      body: "A la izquierda está todo el panel agrupado por temas. Durante el tutorial te vamos a pedir que abras cada módulo desde acá: así memorizás el camino real de trabajo.",
      bullets: [
        "Operación: dashboard, pedidos y cotizaciones.",
        "Catálogo: productos y marcas.",
        "Precios y visibilidad: márgenes, descuentos, qué ve cada cliente y listas compartibles.",
        "CRM: clientes y usuarios.",
      ],
      tip: "Podés abrir o cerrar cada grupo tocando su título.",
    },
    {
      id: "admin-dashboard",
      route: "/admin",
      target: "dash-stats",
      title: "Dashboard: el pulso del día",
      body: "Estas tarjetas resumen la actividad reciente. No se editan acá: son un atajo visual para saber si hay pedidos nuevos, cotizaciones en curso o movimiento comercial.",
      affects: "Los números salen de Pedidos, Cotizaciones y Clientes.",
    },
    {
      id: "admin-dash-crm",
      route: "/admin",
      target: "dash-crm",
      title: "Resumen CRM",
      body: "Más abajo ves un vistazo de clientes y actividad. Desde acá podés saltar a una ficha, pero el alta y la edición vive en CRM → Clientes.",
    },

    // —— CLIENTES ——
    {
      id: "goto-clients",
      route: "/admin",
      target: "nav-link-clients",
      title: "Abrí Clientes",
      body: "En el menú, dentro de CRM, hacé click en «Clientes». Nosotros no cambiamos la pantalla por vos: ese click es el hábito que vas a repetir todos los días.",
      requirePath: "/admin/clients",
      autoAdvanceOnRoute: true,
      tip: "Si el grupo CRM está cerrado, abrilo tocando el título «CRM».",
    },
    {
      id: "clients-list",
      route: "/admin/clients",
      target: "page-header",
      title: "Lista de clientes",
      body: "Acá viven todas las empresas. Cada fila es una cuenta comercial: contactos, usuarios del portal, pedidos y cotizaciones cuelgan de esta ficha.",
      bullets: [
        "Buscá por razón social, fantasía o CUIT.",
        "Entrá a una ficha para ver el historial completo.",
      ],
    },
    {
      id: "clients-new",
      route: "/admin/clients",
      target: "clients-new-btn",
      title: "Cómo crear un cliente",
      body: "Tocá «Nuevo cliente». Se abre un asistente en 2 pasos. No hace falta que lo completes ahora: mirá qué hace cada campo cuando lo uses.",
      bullets: [
        "Paso 1 — Empresa: Razón social (obligatorio), Nombre de fantasía, CUIT, Segmento (Integrador, Corporativo, Educación, Residencial, Gobierno, Rental) y Responsable interno.",
        "Paso 2 — Contacto: nombre, cargo, email, teléfono y WhatsApp.",
        "Checkbox «Crear también un usuario del portal para este contacto»: si lo tildás, además de la empresa se crea un login para que esa persona entre al portal B2B.",
        "Si tildás el checkbox, pedí nombre + email del contacto. La contraseña inicial es opcional: si la dejás vacía, el sistema genera una temporal y te la muestra una sola vez.",
        "Si NO tildás el checkbox, el cliente queda cargado sin acceso al portal (útil para cuentas solo comerciales).",
      ],
      tip: "Después del alta podés sumar más contactos y usuarios desde la ficha del cliente.",
      affects: "El cliente define precios, visibilidad de catálogo y a quién le llegan los pedidos del portal.",
    },
    {
      id: "clients-after",
      route: "/admin/clients",
      target: "page-header",
      title: "Qué pasa después de crear",
      body: "Al guardar, entrás a la ficha del cliente. Ahí centralizás contactos, usuarios del portal, pedidos, cotizaciones, precios y visibilidad.",
      bullets: [
        "Desde la ficha podés crear una cotización ya vinculada a esa empresa.",
        "También podés editar datos, desactivar la cuenta o gestionar accesos sin borrar el historial.",
      ],
    },

    // —— USUARIOS ——
    {
      id: "goto-users",
      route: "/admin/clients",
      target: "nav-link-users",
      title: "Abrí Usuarios",
      body: "Siguiente parada: CRM → Usuarios. Hacé click en «Usuarios» en el menú.",
      requirePath: "/admin/users",
      autoAdvanceOnRoute: true,
    },
    {
      id: "users-list",
      route: "/admin/users",
      target: "page-header",
      title: "Usuarios del sistema",
      body: "Acá están quienes entran al panel o al portal. Un usuario de portal siempre pertenece a un cliente; un administrador opera el panel.",
    },
    {
      id: "users-new",
      route: "/admin/users",
      target: "users-new-btn",
      title: "Cómo crear un usuario",
      body: "Tocá «Nuevo usuario». Elegí el tipo con cuidado: eso define qué interfaz ve.",
      bullets: [
        "Cliente del portal: ve catálogo y precios de su empresa; debe estar vinculado a un Cliente.",
        "Administrador: gestiona la operación del panel.",
        "Super admin: acceso completo (solo si quien crea también es super admin).",
        "Contraseña: podés generar una temporal (se muestra una vez) o escribirla vos.",
        "Permisos avanzados: un rol personalizado puede limitar menús y acciones dentro del admin.",
      ],
      affects: "Sin usuario de portal, el cliente no puede pedir solo; sin admin, no hay quien responda.",
    },

    // —— PRODUCTOS ——
    {
      id: "goto-products",
      route: "/admin/users",
      target: "nav-link-products",
      title: "Abrí Productos",
      body: "Vamos al catálogo. En el menú, grupo Catálogo → «Productos».",
      requirePath: "/admin/products",
      autoAdvanceOnRoute: true,
      tip: "Durante el tutorial: mirá y navegá. No uses Guardar, Enviar, Emitir ni Crear.",
    },
    {
      id: "products-list",
      route: "/admin/products",
      target: "page-header",
      title: "Catálogo de productos",
      body: "Cada ficha alimenta el portal, las cotizaciones y las listas compartibles. Lo incompleto o inactivo impacta en lo que el cliente puede ver y comprar.",
      bullets: [
        "Filtrá por marca, categoría, stock, activos, sin foto o sin descripción.",
        "«Nuevo producto» abre el alta (en el tutorial solo la miramos).",
        "La edición en masa sirve para activar/desactivar o enriquecer varios a la vez.",
      ],
    },
    {
      id: "products-tabs",
      route: "/admin/products",
      target: "products-tabs",
      title: "Catálogo vs Crestron Home",
      body: "Las pestañas separan el catálogo general de los productos pensados para Crestron Home. Usá la que corresponda al trabajo del día.",
    },
    {
      id: "products-open",
      route: "/admin/products",
      target: "products-open-row",
      title: "Abrí una ficha existente",
      body: "Tu turno: entrá a cualquier producto de la lista. Vamos a recorrer qué hay adentro y de dónde sale cada dato.",
      requirePath: "/admin/products",
      requirePathMode: "child",
      requirePathExclude: ["new"],
      autoAdvanceOnRoute: true,
      tip: "No hace falta editar nada: con abrir la ficha alcanza.",
    },
    {
      id: "product-nav",
      route: "/admin/products",
      target: "product-nav",
      title: "Mapa de la ficha",
      body: "Arriba tenés anclas a cada bloque: Datos generales, Etiquetas, Asistente IA, Imágenes, Opciones, Accesorios y Datos del proveedor.",
    },
    {
      id: "product-data",
      route: "/admin/products",
      target: "product-data",
      title: "Datos generales: manual vs importado",
      body: "Núcleo comercial del producto. Muchos campos vienen de Excel/sync o del portal del fabricante; otros se completan a mano. El sello de fecha bajo un campo marca la última actualización (típico de import/sync).",
      bullets: [
        "Identificación: COD. TANGO, SKU proveedor, modelo — Excel/ERP o alta manual.",
        "Clasificación: marca, proveedor, rubro, subrubro, familia, tipo, Principal/Accesorio.",
        "NCM y aranceles: posición, AEC, DIE, TE, origen, peso, volumen.",
        "Cadena de precios: costo USD, descuentos y coeficientes. El PVP no se tipea: lo calcula el motor.",
        "Disponibilidad: estado de stock y cantidad.",
        "Descripciones: a mano o con «Generar con IA» (badge Desc. IA).",
        "Checkboxes: activo, personalizable, exige principal, Crestron Home.",
      ],
      affects: "Portal, cotizaciones, listas compartibles y el motor de precios.",
      tip: "No pulses Guardar abajo: si solo mirás, no se persiste nada.",
    },
    {
      id: "product-labels",
      route: "/admin/products",
      target: "product-labels",
      title: "Etiquetas",
      body: "Agrupan y filtran el catálogo (ofertas, líneas, campañas). Se asignan a mano; no las inventa la IA.",
    },
    {
      id: "product-ai",
      route: "/admin/products",
      target: "product-ai",
      title: "Qué hace la IA (y qué no)",
      body: "El Asistente IA sugiere clasificación y permite editar prompts globales de descripciones. Los textos se generan en Descripciones del formulario.",
      bullets: [
        "SÍ: sugerir marca/categoría/familia, regenerar textos, badge Desc. IA.",
        "NO: no inventa costos, NCM, stock ni fotos (las fotos tienen otro flujo).",
        "Cambiar prompts afecta futuras generaciones en todo el catálogo.",
      ],
      tip: "No apliques sugerencias ni regeneres textos en el tutorial.",
    },
    {
      id: "product-images",
      route: "/admin/products",
      target: "product-images",
      title: "Imágenes: de dónde salen",
      body: "Las fotos pueden venir de varias fuentes; en cada una suele verse el origen.",
      bullets: [
        "Subida manual desde tu compu.",
        "Búsqueda en Google vía Serper (opcional).",
        "Import/sync del proveedor o datos del portal del fabricante.",
        "Una se marca como principal: es la del portal.",
      ],
      tip: "No subas ni adjuntes imágenes en el paseo.",
    },
    {
      id: "product-options",
      route: "/admin/products",
      target: "product-options",
      title: "Opciones configurables",
      body: "Variantes (color, pack, etc.) y eventual delta de precio. Es carga manual de catálogo, no IA.",
    },
    {
      id: "product-accessories",
      route: "/admin/products",
      target: "product-accessories",
      title: "Accesorios compatibles",
      body: "Vinculás otros productos como accesorios opcionales u obligatorios para kits y sugerencias en el portal.",
      affects: "Cotizaciones y portal pueden mostrarlos junto al principal.",
    },
    {
      id: "product-supplier",
      route: "/admin/products",
      target: "product-supplier",
      title: "Datos del proveedor / páginas externas",
      body: "Material traído del portal del fabricante (specs, documentos, HTML, badges, URL, medidas). Suele verse Enriquecido/Traducido con fecha.",
      bullets: [
        "Es referencia externa, no el formulario comercial editable.",
        "Si está vacío, todavía no se enriqueció o no hay fuente.",
      ],
    },
    {
      id: "products-new",
      route: "/admin/products",
      target: "products-new-btn",
      title: "Crear de cero (solo mirar)",
      body: "Abrí «Nuevo producto» para ver el alta vacía. Guardar crearía un producto real: en el tutorial solo observá y no guardes.",
      requirePath: "/admin/products/new",
      requirePathMode: "exact",
      autoAdvanceOnRoute: true,
    },
    {
      id: "products-new-form",
      route: "/admin/products/new",
      target: "page-header",
      title: "Alta manual vs importación",
      body: "El alta usa el mismo formulario de datos generales. El catálogo masivo entra por Importar Excel / Sincronización; esta pantalla es para excepciones.",
      bullets: [
        "Alta manual: un producto a la vez.",
        "Excel/sync: trae costos y códigos de golpe; después se enriquece con IA/fotos.",
        "En el tutorial no guardamos el alta.",
      ],
    },

    // —— MARCAS ——
    {
      id: "goto-brands",
      route: "/admin/products",
      target: "nav-link-brands",
      title: "Abrí Marcas",
      body: "Catálogo → «Marcas». Click en el menú.",
      requirePath: "/admin/brands",
      autoAdvanceOnRoute: true,
    },
    {
      id: "brands",
      route: "/admin/brands",
      target: "page-header",
      title: "Marcas",
      body: "Las marcas ordenan el catálogo y son el ancla más usada en reglas de precio y visibilidad.",
      bullets: [
        "Al crear: Nombre, logo, descripción y checkbox «Marca activa».",
        "Si desactivás una marca, deja de usarse en filtros y reglas nuevas.",
        "Eliminar una marca deja los productos sin marca (no borra productos).",
      ],
      affects: "Filtros del portal, márgenes, descuentos y visibilidad por marca.",
    },

    // —— MÁRGENES ——
    {
      id: "goto-margins",
      route: "/admin/brands",
      target: "nav-link-margins",
      title: "Abrí Márgenes",
      body: "Precios y visibilidad → «Márgenes».",
      requirePath: "/admin/margins",
      autoAdvanceOnRoute: true,
    },
    {
      id: "margins",
      route: "/admin/margins",
      target: "page-header",
      title: "Márgenes: cómo se forma el precio",
      body: "Acá definís el markup. El precio de lista sale de costo nacionalizado × markup. Después se restan descuentos.",
      bullets: [
        "¿Para quién?: todos los clientes, o uno/varios clientes.",
        "¿Sobre qué?: todo el catálogo, marca(s), producto(s), categoría, familia o proveedor.",
        "¿Cómo?: Markup × (ej. 1,35) o Margen %.",
        "Una regla más específica gana: cliente+producto > cliente+marca > global.",
        "Checkbox «Regla activa»: apagar sin borrar.",
      ],
      tip: "Markup 2,75 significa ×2,75 (no se le suma 1).",
      affects: "Portal, cotizaciones y listas compartibles usan este precio.",
    },

    // —— DESCUENTOS ——
    {
      id: "goto-discounts",
      route: "/admin/margins",
      target: "nav-link-discounts",
      title: "Abrí Descuentos",
      body: "Precios y visibilidad → «Descuentos».",
      requirePath: "/admin/discounts",
      autoAdvanceOnRoute: true,
    },
    {
      id: "discounts",
      route: "/admin/discounts",
      target: "page-header",
      title: "Descuentos comerciales",
      body: "Se restan después del margen. Sirven para acuerdos por cliente o campañas por marca/producto.",
      bullets: [
        "Misma lógica de alcance que márgenes (quién + qué).",
        "También existen descuentos en la ficha del producto y etiquetas de oferta del fabricante.",
        "Precedencia típica: descuento de cliente específico > ficha de producto > reglas generales.",
      ],
      affects: "Baja el precio final sin tocar el costo ni el markup base.",
    },

    // —— VISIBILIDAD ——
    {
      id: "goto-visibility",
      route: "/admin/discounts",
      target: "nav-link-visibility",
      title: "Abrí Visibilidad",
      body: "Precios y visibilidad → «Visibilidad por cliente».",
      requirePath: "/admin/visibility",
      autoAdvanceOnRoute: true,
    },
    {
      id: "visibility",
      route: "/admin/visibility",
      target: "page-header",
      title: "Qué ve cada cliente",
      body: "Por defecto el cliente ve todo el catálogo activo. Acá cargás excepciones.",
      bullets: [
        "Elegí el cliente (obligatorio).",
        "Alcance: marcas, proveedores, categorías, familias o productos.",
        "«Ocultar»: lista negra (no lo ve).",
        "«Permitir explícitamente»: lista blanca avanzada.",
        "Ocultar una marca esconde todos sus productos para ese cliente.",
      ],
      tip: "Si en el portal «faltan» productos, revisá primero esta pantalla.",
      affects: "El portal y las listas compartibles respetan estas reglas.",
    },

    // —— LISTAS COMPARTIBLES ——
    {
      id: "goto-share-lists",
      route: "/admin/visibility",
      target: "nav-link-share-lists",
      title: "Abrí Listas compartibles",
      body: "Precios y visibilidad → «Listas compartibles».",
      requirePath: "/admin/share-lists",
      autoAdvanceOnRoute: true,
    },
    {
      id: "share-lists",
      route: "/admin/share-lists",
      target: "share-lists-new-btn",
      title: "Listas de precios compartibles",
      body: "Armás un recorte de catálogo y lo compartís con un link público (sin login). Ideal para enviar precios a un cliente o proyecto puntual. Tocá «Nueva lista» para crear una.",
      bullets: [
        "Nombre, descripción visible en el link, estado (Borrador / Activa / Archivada).",
        "«Precios para cliente»: aplica márgenes, descuentos y visibilidad de esa empresa.",
        "Vencimiento del link, mostrar/ocultar SKU, stock o precios.",
        "Filtros: principales, accesorios, stock, descuento, marcas, categorías, productos puntuales.",
        "Cuando está Activa, copiá el link y compartilo. Podés regenerarlo si hace falta invalidar el anterior.",
      ],
      affects: "Quien abre el link ve el catálogo filtrado con la política de precios elegida.",
    },

    // —— PEDIDOS ——
    {
      id: "goto-requests",
      route: "/admin/share-lists",
      target: "nav-link-requests",
      title: "Abrí Pedidos",
      body: "Operación → «Pedidos».",
      requirePath: "/admin/requests",
      autoAdvanceOnRoute: true,
      tip: "Seguimos en modo tutorial: no envíes respuestas ni cambies estados de verdad.",
    },
    {
      id: "requests-list",
      route: "/admin/requests",
      target: "page-header",
      title: "Bandeja de pedidos",
      body: "Acá llegan los pedidos que el cliente envía desde el portal (no se crean desde el admin). Es la bandeja comercial del día.",
      bullets: [
        "Estados: Nuevo, En revisión, Respondido, Confirmado, Rechazado, Cerrado.",
        "Tipos: Cotización, Compra, Consulta.",
        "Filtros por búsqueda, tipo y fechas; chips de estado arriba.",
        "«Abrir» / «Responder» entra al detalle.",
      ],
      affects: "Conecta el portal del cliente con Cotizaciones.",
    },
    {
      id: "requests-open",
      route: "/admin/requests",
      target: "requests-open-row",
      title: "Entrá a un pedido existente",
      body: "Tu turno: abrí cualquier pedido de la lista. Vamos a ver qué se edita adentro sin guardar cambios.",
      requirePath: "/admin/requests",
      requirePathMode: "child",
      autoAdvanceOnRoute: true,
    },
    {
      id: "request-status",
      route: "/admin/requests",
      target: "request-status",
      title: "Línea de estados",
      body: "El stepper muestra el camino del pedido (Nuevo → En revisión → Respondido → Confirmado). Rechazado y Cerrado son salidas laterales.",
      tip: "Más abajo, en «Cambiar estado», están los botones de acción rápida — no los uses en el tutorial.",
    },
    {
      id: "request-items",
      route: "/admin/requests",
      target: "request-items",
      title: "Productos del pedido",
      body: "Ves lo que pidió el cliente y, si el equipo sugirió alternativas, esas líneas aparte. Se pueden ajustar cantidades o sugerir productos.",
      bullets: [
        "Lo pedido por el cliente vs sugerencias del equipo.",
        "Precios con la política de ese cliente (márgenes/descuentos).",
        "En el tutorial no modifiques cantidades ni agregues sugerencias.",
      ],
    },
    {
      id: "request-reply",
      route: "/admin/requests",
      target: "request-reply",
      title: "Responder al cliente",
      body: "Es el paso principal del día a día: redactás la respuesta visible en el portal, podés pedir ayuda a la IA, elegís en qué estado queda el pedido al enviar, y enviás.",
      bullets: [
        "Texto oficial para el cliente + historial de conversación.",
        "«Redactar con IA» sugiere un borrador (revisalo siempre).",
        "Al enviar, el cliente lo ve en su portal.",
      ],
      tip: "No envíes la respuesta en el tutorial: con leer el bloque alcanza.",
    },
    {
      id: "request-quote",
      route: "/admin/requests",
      target: "request-quote",
      title: "Cotización desde el pedido",
      body: "Desde acá generás una cotización ligada al pedido, abrís una ya creada o adjuntás el PDF como respuesta.",
      affects: "El puente Pedido → Cotización mantiene trazabilidad con el cliente.",
      tip: "No generes una cotización real ahora; eso lo vemos en el módulo siguiente.",
    },
    {
      id: "request-status-actions",
      route: "/admin/requests",
      target: "request-status-actions",
      title: "Cambiar estado sin responder",
      body: "Tomar y revisar, marcar respondida, confirmar, rechazar o cerrar — sin mandar texto. Útil para ordenar la bandeja.",
      tip: "No pulses estos botones en el tutorial: cambiarían el pedido real.",
    },
    {
      id: "requests-create-note",
      route: "/admin/requests",
      target: "page-header",
      title: "¿Cómo se crea un pedido de cero?",
      body: "En el admin no hay «Nuevo pedido». Los crea el cliente (o vos en Modo cliente) desde el portal: carrito → enviar pedido. Después aparece acá para responderlo.",
      bullets: [
        "Portal → catálogo → carrito → enviar.",
        "Modo cliente (al final del tutorial) sirve para probar ese circuito.",
        "Todo lo que envíes desde el portal sí se guarda: no lo hagas en el paseo.",
      ],
    },

    // —— COTIZACIONES ——
    {
      id: "goto-quotes",
      route: "/admin/requests",
      target: "nav-link-quotes",
      title: "Abrí Cotizaciones",
      body: "Operación → «Cotizaciones».",
      requirePath: "/admin/quotes",
      autoAdvanceOnRoute: true,
      tip: "No emitas ni guardes cotizaciones durante el tutorial.",
    },
    {
      id: "quotes-list",
      route: "/admin/quotes",
      target: "page-header",
      title: "Lista de cotizaciones",
      body: "Propuestas formales con diseño Soundtec: ítems, textos, PDF y emisión.",
      bullets: [
        "Estados: Borrador, En revisión, Lista, Emitida, Reemplazada, Archivada.",
        "«Nueva cotización»: flujo completo por pasos.",
        "«Cotización rápida»: una sola pantalla para listas cortas.",
        "Memoria histórica: base de cotizaciones viejas para reusar criterio.",
      ],
    },
    {
      id: "quotes-open",
      route: "/admin/quotes",
      target: "quotes-open-row",
      title: "Abrí una cotización existente",
      body: "Tu turno: entrá a Editar en cualquier fila. Vamos a recorrer el asistente paso a paso sin emitir.",
      requirePath: "/admin/quotes",
      requirePathMode: "child",
      requirePathExclude: ["new", "quick", "history"],
      autoAdvanceOnRoute: true,
    },
    {
      id: "quote-wizard",
      route: "/admin/quotes",
      target: "quote-wizard",
      title: "Asistente en 7 pasos",
      body: "La barra superior es el mapa: Encabezado → Brief → Módulos → Productos → Textos con IA → Imágenes → Emitir. Podés saltar entre pasos sin perder el borrador… pero en el tutorial no guardes de más.",
    },
    {
      id: "quote-header",
      route: "/admin/quotes",
      target: "quote-header",
      title: "Paso Encabezado",
      body: "Cliente, contacto, proyecto, clasificación interna y datos de cabecera del PDF. Sin cliente no se puede emitir al final.",
      tip: "Si vino desde un pedido, vas a ver el vínculo al pedido de origen.",
    },
    {
      id: "quote-brief",
      route: "/admin/quotes",
      target: "quote-brief",
      title: "Brief y generación",
      body: "Acá contás qué hay que cotizar y podés subir planos/fotos. La IA usa este brief para proponer módulos, productos y textos.",
      tip: "Generar con IA no «rompe» nada solo, pero puede reescribir contenido: en el tutorial no dispares generadores.",
    },
    {
      id: "quote-modules",
      route: "/admin/quotes",
      target: "quote-add-module",
      title: "Módulos del documento",
      body: "Elegís qué bloques entran al PDF (apertura, propuesta, condiciones, etc.). Incluir/excluir cambia el documento, no el precio.",
    },
    {
      id: "quote-bom",
      route: "/admin/quotes",
      target: "quote-bom",
      title: "Productos / BOM",
      body: "La lista de ítems por ambiente o zona: altas, cantidades, precios del motor, notas. Es el corazón comercial de la cotización.",
      bullets: [
        "Agregar zona / ambiente para organizar.",
        "Buscar productos del catálogo o pegar SKUs.",
        "Los precios respetan márgenes y descuentos del cliente.",
      ],
      tip: "No agregues ni borres ítems reales en el tutorial.",
    },
    {
      id: "quote-texts",
      route: "/admin/quotes",
      target: "quote-generate-texts",
      title: "Textos con IA",
      body: "Redacción de bloques narrativos (propuesta, criterios, etc.). Se pueden regenerar y editar a mano después.",
      tip: "No regenerues textos ahora.",
    },
    {
      id: "quote-issue",
      route: "/admin/quotes",
      target: "quote-issue",
      title: "Emitir (no lo hagas en el tutorial)",
      body: "Checklist final, condiciones, enviar a revisión o emitir COT, y descargas PDF/Word/Excel. Emitir deja la cotización formal para el cliente.",
      affects: "Una vez emitida, el documento queda registrado y puede adjuntarse a un pedido.",
      tip: "No pulses Emitir ni Enviar a revisión en el paseo.",
    },
    {
      id: "quotes-new",
      route: "/admin/quotes",
      target: "quotes-new-btn",
      title: "Crear cotización completa de cero",
      body: "Abrí «Nueva cotización». Vas a ver el alta previa (cliente, brief, tipo de documento). Crearla sí guarda un borrador: en el tutorial solo mirá el formulario y no confirmes la creación.",
      requirePath: "/admin/quotes/new",
      requirePathMode: "exact",
      autoAdvanceOnRoute: true,
    },
    {
      id: "quotes-new-form",
      route: "/admin/quotes/new",
      target: "quote-new-client",
      title: "Alta: cliente y proyecto",
      body: "Paso 1 del alta: cliente (u «asignar después»), contacto y nombre del proyecto. Es lo que sale en el encabezado del PDF.",
      tip: "No pulses Crear cotización.",
    },
    {
      id: "quotes-new-brief",
      route: "/admin/quotes/new",
      target: "quote-new-brief",
      title: "Alta: brief y planos",
      body: "Qué hay que cotizar, en lenguaje simple. La IA lo usa después. Podés adjuntar planos o fotos.",
    },
    {
      id: "quotes-new-type",
      route: "/admin/quotes/new",
      target: "quote-new-type",
      title: "Alta: tipo de documento",
      body: "Extensión (resumido / técnico / premium) y diseño del PDF. Después seguís en el asistente de 7 pasos.",
    },
    {
      id: "quotes-quick",
      route: "/admin/quotes",
      target: "quotes-quick-btn",
      title: "Cotización rápida de cero",
      body: "Abrí «Cotización rápida». Es el atajo: cliente, referencia, plantilla, ítems y emitir/guardar en una pantalla.",
      requirePath: "/admin/quotes/quick",
      requirePathMode: "exact",
      autoAdvanceOnRoute: true,
    },
    {
      id: "quotes-quick-form",
      route: "/admin/quotes/quick",
      target: "quote-quick-form",
      title: "Formulario rápido",
      body: "Ideal para una lista corta. Podés guardar borrador o crear y emitir PDF, e incluso adjuntarlo a un pedido abierto.",
      bullets: [
        "Cliente + referencia + validez + plantilla.",
        "Buscar productos o pegar SKUs.",
        "No uses Guardar / Emitir en el tutorial.",
      ],
    },

    // —— MODO CLIENTE ——
    {
      id: "goto-mode",
      route: "/admin/quotes",
      target: "nav-link-dashboard",
      title: "Volvé al Dashboard",
      body: "Para el último tramo, abrí «Dashboard» en Operación.",
      requirePath: "/admin",
      autoAdvanceOnRoute: true,
    },
    {
      id: "mode-client",
      route: "/admin",
      target: "mode-client",
      title: "Probar el portal (Modo cliente)",
      body: "El botón «Modo cliente» abre el portal con tu mismo login. Sirve para validar catálogo, precios, carrito y el pedido de punta a punta.",
      bullets: [
        "No cambia de usuario: es la misma sesión en otra interfaz.",
        "Para volver, en el portal usá «Modo admin».",
        "Lo que ves en el portal depende de visibilidad y precios configurados en el admin.",
      ],
      tip: "Hacé el circuito: portal → agregar al carrito → enviar pedido → verlo en Admin → Pedidos.",
    },
    {
      id: "help-dock",
      route: "/admin",
      target: "help-dock",
      title: "Ayuda siempre a mano",
      body: "El botón Ayuda abre el asistente, recorridos por pantalla y este tutorial. Si querés repetir el paseo: Ayuda → «Empezar guía de nuevo».",
    },
    {
      id: "admin-done",
      route: "/admin",
      title: "Listo para operar",
      body: "Ya recorriste el circuito completo. Sugerencia práctica: creá un cliente de prueba, asignale un margen, mirá un producto en Modo cliente y armá una cotización rápida.",
      tip: "El progreso queda en tu usuario. Podés reiniciar la guía cuando quieras.",
    },
  ],
};

export const PORTAL_ONBOARDING: OnboardingTour = {
  id: "portal",
  title: "Tutorial del portal",
  subtitle: "Catálogo, listas y pedidos",
  welcomeTitle: "Bienvenido al portal Soundtec",
  welcomeBody:
    "Desde acá consultás el catálogo con tus precios, armás listas y enviás pedidos. Te mostramos el circuito; los clicks los hacés vos.",
  steps: [
    {
      id: "portal-home",
      route: "/portal",
      target: "portal-home-hero",
      title: "Tu inicio",
      body: "Buscá por modelo, marca o palabra clave. Los precios que ves ya incluyen las condiciones de tu cuenta.",
    },
    {
      id: "portal-nav",
      route: "/portal",
      target: "portal-nav",
      title: "Navegación",
      body: "Catálogo, Favoritos, Mis listas y Mis pedidos. En el celular también están en la barra inferior.",
      tip: "Para cambiar de sección, tocá el ítem del menú (no hace falta que el tutorial lo haga por vos).",
    },
    {
      id: "goto-portal-catalog",
      route: "/portal",
      target: "portal-nav",
      title: "Abrí el Catálogo",
      body: "Hacé click en «Catálogo» en el menú superior (o en la barra de abajo si estás en el teléfono).",
      requirePath: "/portal/products",
      autoAdvanceOnRoute: true,
    },
    {
      id: "portal-catalog",
      route: "/portal/products",
      target: "page-header",
      title: "Catálogo con tus precios",
      body: "Solo ves lo disponible para tu empresa. El precio ya tiene márgenes y descuentos aplicados por Soundtec.",
      bullets: [
        "Filtrá por stock, descuento o favoritos cuando lo necesites.",
        "Abrí un producto para ver ficha y agregar al carrito.",
      ],
    },
    {
      id: "goto-portal-wishlist",
      route: "/portal/products",
      target: "portal-nav",
      title: "Abrí Favoritos",
      body: "En el menú, tocá «Favoritos».",
      requirePath: "/portal/wishlist",
      autoAdvanceOnRoute: true,
    },
    {
      id: "portal-wishlist",
      route: "/portal/wishlist",
      target: "page-header",
      title: "Favoritos",
      body: "Es tu selección personal para volver rápido. No envía nada a Soundtec hasta que armes un pedido.",
    },
    {
      id: "goto-portal-lists",
      route: "/portal/wishlist",
      target: "portal-nav",
      title: "Abrí Mis listas",
      body: "En el menú, tocá «Mis listas».",
      requirePath: "/portal/lists",
      autoAdvanceOnRoute: true,
    },
    {
      id: "portal-lists",
      route: "/portal/lists",
      target: "page-header",
      title: "Mis listas",
      body: "Listas de trabajo por obra o proyecto. Podés reutilizarlas al armar un pedido.",
    },
    {
      id: "portal-cart",
      route: "/portal/lists",
      target: "portal-cart",
      title: "Carrito / borrador",
      body: "Mientras cargás productos se arma un borrador. Cuando esté listo, lo enviás al equipo Soundtec.",
      affects: "Al enviar, el pedido aparece en Admin → Pedidos.",
    },
    {
      id: "goto-portal-requests",
      route: "/portal",
      target: "portal-nav",
      title: "Abrí Mis pedidos",
      body: "En el menú, tocá «Mis pedidos».",
      requirePath: "/portal/requests",
      autoAdvanceOnRoute: true,
    },
    {
      id: "portal-requests",
      route: "/portal/requests",
      target: "page-header",
      title: "Mis pedidos",
      body: "Historial de lo enviado y las respuestas (incluida una cotización formal si te la adjuntan).",
    },
    {
      id: "portal-done",
      route: "/portal",
      title: "Ya podés pedir",
      body: "Circuito listo. Empezá por el catálogo, agregá al carrito y enviá tu primer pedido.",
      tip: "Si también usás el panel, «Modo admin» arriba a la derecha te lleva de vuelta.",
    },
  ],
};

export function tourForSurface(surface: "admin" | "portal"): OnboardingTour {
  return surface === "admin" ? ADMIN_ONBOARDING : PORTAL_ONBOARDING;
}
