import type { OnboardingTour } from "./types";

/** Paseo de bienvenida del admin: ventas, clientes y catálogo (sin sync/imports). */
export const ADMIN_ONBOARDING: OnboardingTour = {
  id: "admin",
  title: "Bienvenida al panel",
  subtitle: "Un paseo corto por ventas, clientes y catálogo",
  welcomeTitle: "Te damos la bienvenida al panel Soundtec",
  welcomeBody:
    "En unos minutos vas a ver cómo se relacionan clientes, catálogo, precios, pedidos y cotizaciones. Podés pausar y retomar cuando quieras desde Ayuda.",
  steps: [
    {
      id: "admin-nav",
      route: "/admin",
      target: "nav-operacion",
      title: "El menú es tu mapa",
      body: "A la izquierda están los módulos agrupados: Operación, Catálogo, Precios, CRM. Tocá una sección para abrirla.",
      tip: "Si no ves un ítem, tu rol no tiene ese permiso.",
    },
    {
      id: "admin-dashboard",
      route: "/admin",
      target: "dash-stats",
      title: "Dashboard",
      body: "Acá ves el pulso del negocio: pedidos, cotizaciones y actividad reciente. Es el punto de partida cada mañana.",
      affects: "Los números salen de Pedidos, Cotizaciones y Clientes.",
    },
    {
      id: "admin-crm",
      route: "/admin",
      target: "dash-crm",
      title: "CRM en un vistazo",
      body: "El resumen de clientes muestra quién está activo y qué merece seguimiento. Desde acá saltás a la ficha.",
      affects: "Se alimenta de Clientes y de la actividad registrada.",
    },
    {
      id: "admin-clients",
      route: "/admin/clients",
      target: "page-header",
      title: "Clientes",
      body: "Cada empresa vive acá: contactos, lista de precios, visibilidad de catálogo y usuarios del portal.",
      tip: "Al crear un cliente podés generar su usuario de portal en el mismo paso.",
      affects: "Define qué ve el portal, qué precios aplica y a quién llegan los pedidos.",
    },
    {
      id: "admin-users",
      route: "/admin/users",
      target: "page-header",
      title: "Usuarios y permisos",
      body: "Administradores, vendedores y usuarios de portal. Los roles custom limitan menús y acciones.",
      tip: "Un usuario de portal siempre debe estar vinculado a una empresa.",
      affects: "Los permisos cambian el menú y qué botones aparecen.",
    },
    {
      id: "admin-products",
      route: "/admin/products",
      target: "page-header",
      title: "Catálogo de productos",
      body: "El corazón del sistema: fichas, marcas, fotos y datos técnicos. Lo que publiques alimenta el portal del cliente.",
      tip: "Filtrá, editá en masa o abrí la ficha para completar descripciones.",
      affects: "Marcas, categorías, márgenes y visibilidad usan estos productos.",
    },
    {
      id: "admin-brands",
      route: "/admin/brands",
      target: "page-header",
      title: "Marcas",
      body: "Organizá el catálogo por marca. Sirve para filtros del portal y para reglas de margen o descuento.",
      affects: "Las reglas de precio y la navegación del catálogo dependen de la marca.",
    },
    {
      id: "admin-margins",
      route: "/admin/margins",
      target: "page-header",
      title: "Márgenes = cómo se forma el precio",
      body: "Markups por marca, familia o producto. El precio de venta sale de costo × margen (− descuentos).",
      tip: "Una regla más específica (producto) gana sobre una general (marca).",
      affects: "Impacta precios del portal, cotizaciones y listas compartibles.",
    },
    {
      id: "admin-discounts",
      route: "/admin/discounts",
      target: "page-header",
      title: "Descuentos",
      body: "Descuentos comerciales por cliente, marca o producto. Se restan después del margen.",
      affects: "Baja el precio final sin tocar el costo ni el markup base.",
    },
    {
      id: "admin-visibility",
      route: "/admin/visibility",
      target: "page-header",
      title: "Visibilidad por cliente",
      body: "Controlás qué marcas o productos ve cada empresa en el portal. Ideal para catálogos selectivos.",
      affects: "Si un producto no se ve en el portal, casi siempre es una regla de visibilidad.",
    },
    {
      id: "admin-requests",
      route: "/admin/requests",
      target: "page-header",
      title: "Pedidos del portal",
      body: "Cuando un cliente arma un carrito y lo envía, llega acá. Podés responder o convertir en cotización.",
      tip: "Desde un pedido podés abrir o crear la cotización vinculada.",
      affects: "Conecta el portal del cliente con Cotizaciones.",
    },
    {
      id: "admin-quotes",
      route: "/admin/quotes",
      target: "page-header",
      title: "Cotizaciones",
      body: "Propuestas formales con diseño Soundtec: ítems, textos, PDF y emisión. También existe la cotización rápida.",
      tip: "«Nueva cotización» = flujo completo. «Cotización rápida» = armar y emitir en una pantalla.",
      affects: "Toma precios del motor (márgenes/descuentos) y puede adjuntarse a un pedido.",
    },
    {
      id: "admin-mode-switch",
      route: "/admin",
      target: "mode-client",
      title: "Probar el portal como cliente",
      body: "«Modo cliente» abre el portal con tu mismo usuario. Validá catálogo y carrito. Volvés con «Modo admin».",
      tip: "No cambia de usuario: es el mismo login en otra interfaz.",
      affects: "Lo que ves en el portal depende de visibilidad y precios del admin.",
    },
    {
      id: "admin-help",
      route: "/admin",
      target: "help-dock",
      title: "Ayuda siempre a mano",
      body: "El botón Ayuda abre el asistente, recorridos por pantalla y tutoriales. Si te perdés, empezá por acá.",
      tip: "También podés reiniciar este paseo de bienvenida desde Ayuda.",
    },
    {
      id: "admin-done",
      route: "/admin",
      title: "Listo para operar",
      body: "Ya recorriste el circuito comercial. Sugerencia: abrí un cliente, mirá un producto y armá una cotización rápida.",
      tip: "El progreso queda guardado en tu usuario. Podés repetir el paseo cuando quieras.",
    },
  ],
};

/** Paseo del portal B2B para usuarios cliente. */
export const PORTAL_ONBOARDING: OnboardingTour = {
  id: "portal",
  title: "Bienvenida al portal",
  subtitle: "Catálogo, listas y pedidos en pocos pasos",
  welcomeTitle: "Bienvenido al portal Soundtec",
  welcomeBody:
    "Desde acá consultás el catálogo con tus precios, armás listas y enviás pedidos. Este paseo te muestra el circuito completo.",
  steps: [
    {
      id: "portal-home",
      route: "/portal",
      target: "portal-home-hero",
      title: "Tu inicio",
      body: "Desde acá buscás productos y ves accesos rápidos al catálogo, favoritos y pedidos.",
    },
    {
      id: "portal-nav",
      route: "/portal",
      target: "portal-nav",
      title: "Navegación",
      body: "Catálogo, Favoritos, Mis listas y Mis pedidos. En el celular también están abajo.",
    },
    {
      id: "portal-catalog",
      route: "/portal/products",
      target: "page-header",
      title: "Catálogo",
      body: "Productos disponibles para tu empresa, con el precio que Soundtec configuró para vos.",
      tip: "Si no ves una marca, tu cuenta puede tener visibilidad limitada.",
      affects: "Los precios los define el equipo Soundtec (márgenes y descuentos).",
    },
    {
      id: "portal-wishlist",
      route: "/portal/wishlist",
      target: "page-header",
      title: "Favoritos",
      body: "Guardá productos para volver rápido. No es un pedido: es tu selección personal.",
    },
    {
      id: "portal-lists",
      route: "/portal/lists",
      target: "page-header",
      title: "Mis listas",
      body: "Listas de trabajo por obra o proyecto. Podés reutilizarlas al armar un pedido.",
    },
    {
      id: "portal-cart",
      route: "/portal",
      target: "portal-cart",
      title: "Carrito / borrador",
      body: "Mientras cargás productos se arma un borrador. Cuando esté listo, lo enviás al equipo Soundtec.",
      affects: "Al enviar, el pedido aparece en Admin → Pedidos.",
    },
    {
      id: "portal-requests",
      route: "/portal/requests",
      target: "page-header",
      title: "Mis pedidos",
      body: "Historial de lo enviado y las respuestas (incluida una cotización formal si te la adjuntan).",
    },
    {
      id: "portal-done",
      route: "/portal",
      title: "Ya podés pedir",
      body: "Recorrido listo. Empezá por el catálogo, agregá productos al carrito y enviá tu primer pedido.",
      tip: "Si también sos admin, «Modo admin» arriba a la derecha te lleva al panel.",
    },
  ],
};

export function tourForSurface(surface: "admin" | "portal"): OnboardingTour {
  return surface === "admin" ? ADMIN_ONBOARDING : PORTAL_ONBOARDING;
}
