export type HelpModule = {
  id: string;
  title: string;
  match: (pathname: string) => boolean;
  simple: string;
  purpose: string;
  fields: string[];
  editable: string;
  notEditable: string;
  config: string;
  tips: string[];
};

export const HELP_MODULES: HelpModule[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    match: (p) => p === "/admin",
    simple: "Resumen: productos, solicitudes pendientes, importaciones, feedback de IA y tickets abiertos.",
    purpose: "Ver de un vistazo qué hay que atender hoy.",
    fields: [
      "Tarjetas: cada número lleva a esa pantalla.",
      "Últimas solicitudes e importaciones: atajos, no se editan acá.",
    ],
    editable: "Nada se edita en el dashboard.",
    notEditable: "Los números son conteos en vivo.",
    config: "No tiene settings propios.",
    tips: ["Si una tarjeta no coincide con lo que ves adentro, reportalo al dev."],
  },
  {
    id: "requests",
    title: "Solicitudes",
    match: (p) => p === "/admin/requests",
    simple: "Lo que el cliente manda desde el portal: cotización, pedido o consulta.",
    purpose: "Filtrar, abrir y responder. El cliente no ve el editor de COT.",
    fields: [
      "Filtros por estado, tipo, texto y fechas.",
      "Estados: enviada, en revisión, respondida, confirmada, rechazada, cerrada.",
    ],
    editable: "Filtros. El contenido se edita adentro de cada solicitud.",
    notEditable: "El cliente escribe el pedido; no se borra el historial.",
    config: "No. Los precios que ves son los del cliente (márgenes y descuentos).",
    tips: ["Abrí una solicitud para responder, adjuntar PDF de COT o crear una cotización."],
  },
  {
    id: "request-detail",
    title: "Detalle de solicitud",
    match: (p) => /^\/admin\/requests\/[^/]+$/.test(p),
    simple: "Responder al cliente, ver productos, crear o adjuntar una COT en PDF.",
    purpose: "La respuesta oficial va al portal. El PDF de cotización es un snapshot, no el editor.",
    fields: [
      "Qué pidió: texto del cliente.",
      "Productos: líneas del pedido, con precios de ese cliente.",
      "Responder: texto oficial + conversación.",
      "Crear cotización / adjuntar PDF: el cliente solo descarga PDF.",
      "Estado: enviada → revisión → respondida / confirmada / rechazada / cerrada.",
    ],
    editable: "Respuesta, mensajes, estado, crear COT, adjuntar PDF.",
    notEditable: "El cliente no entra al live editor. No regenera el PDF desde el portal.",
    config: "Permiso quotes.create para armar COT. Cotizaciones se configuran en Settings → Cotizaciones.",
    tips: [
      "Adjuntar PDF genera un snapshot en ese momento.",
      "Si el cliente pide cambios, se trabaja otra versión de la COT y se adjunta de nuevo.",
    ],
  },
  {
    id: "quotes",
    title: "Cotizaciones",
    match: (p) => p === "/admin/quotes",
    simple: "Lista de propuestas. Nueva COT o memoria histórica (Excel viejo).",
    purpose: "Abrir borradores, emitidas y el historial de planillas 5.0.",
    fields: ["Filtros, Nueva cotización, Memoria histórica, atajo a plantilla."],
    editable: "Crear y abrir COT si tenés permiso.",
    notEditable: "Una emitida no se reescribe: se revisa o se hace otra versión.",
    config: "Settings → Cotizaciones. Historial: Cotizaciones → Memoria histórica.",
    tips: ["Primero tipo de sala y escala; después el documento."],
  },
  {
    id: "quotes-new",
    title: "Nueva cotización",
    match: (p) => p === "/admin/quotes/new",
    simple: "Alta: clasificación interna, cliente opcional y prompt. Reserva el número.",
    purpose: "Dejar tipo/escala para sugerir equipos de COT parecidas.",
    fields: [
      "Tipo de sala y escala: internos, no van al PDF.",
      "Cliente: sin cliente no se emite.",
      "Referencia, contacto, layout, perfil de contenido.",
      "Qué querés armar: prompt. Planos: PDF o fotos.",
    ],
    editable: "Todo el formulario. Clasificadores se editan en Settings.",
    notEditable: "El número se reserva al crear. La plantilla maestra no se toca acá.",
    config: "Clasificadores, plantilla y numeración en Settings → Cotizaciones.",
    tips: ["Sin prompt igual sugerimos según tipo y escala."],
  },
  {
    id: "quote-editor",
    title: "Editor de cotización",
    match: (p) => /^\/admin\/quotes\/[^/]+$/.test(p) && !p.endsWith("/new") && !p.endsWith("/print"),
    simple: "Siete pasos + documento a la derecha. El cliente no ve esto.",
    purpose: "Armar la propuesta, generar IA, planilla por ambientes y emitir o exportar PDF.",
    fields: [
      "1 Datos: clasificación, cliente, referencia.",
      "2 Brief y planos: Generar propuesta (no pisa texto fijo ni inventa precios).",
      "3 Plantilla: incluir/apagar módulos; agregar módulo extra.",
      "4 Planilla: productos, ambientes, subtotales.",
      "5 Textos: módulos de proyecto; fijar evita que la IA los pise.",
      "6 Imágenes: foto de producto de ESTA COT; marcas/ISO son corporativas.",
      "7 Emitir: condiciones y freeze. Genera PDF snapshot.",
    ],
    editable: "Hasta emitir: textos de proyecto, planilla, extras, fotos de la COT, condiciones de la COT.",
    notEditable:
      "Presentación, marcas, ISO, condiciones de plantilla no se reescriben con Generar. Emitida = solo lectura.",
    config: "Plantilla visual, clasificadores y borradores en Settings → Cotizaciones.",
    tips: [
      "Regenerar descripción corta la guarda en el producto del catálogo.",
      "Quitar ambiente no borra equipos: vuelven a general.",
    ],
  },
  {
    id: "quotes-history",
    title: "Memoria histórica",
    match: (p) => p.startsWith("/admin/quotes/history"),
    simple: "Excel de planillas 5.0: qué se cotizó junto. Sin precios.",
    purpose: "Al generar una propuesta, sugerir compañeros de la misma hoja.",
    fields: ["Subir Excel. Se ignoran hojas LIBRE. Cada hoja = líneas texto + cantidad."],
    editable: "Sólo cargar el archivo. No se linkea cada línea a un producto.",
    notEditable: "No trae precios. No elige sola una planilla por cliente.",
    config: "Permiso quotes.manage_library.",
    tips: ["Los accesorios de la planilla salen del catálogo (AccessoryRelation), no de este Excel."],
  },
  {
    id: "feedback",
    title: "Feedback de IA",
    match: (p) => p.startsWith("/admin/feedback"),
    simple: "Qué dijeron los usuarios de textos o sugerencias de IA.",
    purpose: "Ver errores reportados sobre contenido generado.",
    fields: ["Veredicto, comentario, pieza de contenido."],
    editable: "Revisar. No reescribe el catálogo solo.",
    notEditable: "El historial de feedback.",
    config: "Settings → Prompts y modelos. Permiso ai.manage.",
    tips: ["Si la IA alucina siempre lo mismo, ajustá el prompt de esa función."],
  },
  {
    id: "products",
    title: "Productos",
    match: (p) => p === "/admin/products",
    simple: "Catálogo: buscar, filtrar, alta manual y pestaña Crestron Home.",
    purpose: "Mantener el listado que usan portal, COT e importaciones.",
    fields: [
      "Filtros: marca, categoría, familia, proveedor, stock, activos, sin foto/desc.",
      "Nuevo producto: alta a mano.",
      "Pestaña Crestron Home: compatibles.",
    ],
    editable: "Alta y ficha. Precios/costos según permiso.",
    notEditable: "El precio de venta se calcula (costo + márgenes + descuentos + NCM). No se tipea el PVP acá.",
    config: "Marcas, categorías, familias, proveedores, márgenes, visibilidad.",
    tips: ["La descripción corta se reutiliza en las COT. Regenerar con IA la guarda en el producto."],
  },
  {
    id: "product-new",
    title: "Nuevo producto",
    match: (p) => p === "/admin/products/new",
    simple: "Alta manual al catálogo.",
    purpose: "Cuando no viene de un Excel.",
    fields: ["Nombre, SKU, marca, costo, categoría, familia, proveedor."],
    editable: "Todos los campos del form.",
    notEditable: "El precio de lista se calcula después.",
    config: "Primero existí marca/categoría si las vas a asignar.",
    tips: ["Después completá fotos y descripción en la ficha."],
  },
  {
    id: "product-detail",
    title: "Ficha de producto",
    match: (p) => /^\/admin\/products\/[^/]+$/.test(p),
    simple: "Datos, fotos, descripciones, accesorios, NCM, visibilidad.",
    purpose: "La fuente de verdad del ítem en portal y COT.",
    fields: [
      "Generales: nombre, SKUs, marca, activo, tipo principal/accesorio.",
      "Descripciones: corta (COT) y larga (ficha). Regenerar con IA guarda en el producto.",
      "Fotos: catálogo. En una COT se puede elegir otra foto para ESA COT.",
      "Costo, descuento propio, posición NCM / arancel.",
      "Accesorios: relaciones fijas que aparecen en la planilla de COT.",
    ],
    editable: "Casi todo si tenés products.edit. Costos/precios según products.prices.view.",
    notEditable: "No pongas el PVP a mano: lo arman márgenes y descuentos.",
    config: "Márgenes, descuentos, visibilidad, NCM.",
    tips: ["Si no gusta la descripción corta, regenerala: las próximas COT usan esa versión."],
  },
  {
    id: "brands",
    title: "Marcas",
    match: (p) => p.startsWith("/admin/brands"),
    simple: "Marcas del catálogo y de las importaciones.",
    purpose: "Agrupar productos y aplicar márgenes por marca.",
    fields: ["Nombre, alta, productos asociados."],
    editable: "Nombre y alta. Borrar/archivar con cuidado si hay productos.",
    notEditable: "Los productos no se recategorizan masivamente acá.",
    config: "Márgenes pueden colgar de la marca.",
    tips: ["Creá la marca antes de importar un Excel de ese fabricante."],
  },
  {
    id: "labels",
    title: "Etiquetas",
    match: (p) => p.startsWith("/admin/labels"),
    simple: "Tags para filtrar productos (color + nombre).",
    purpose: "Clasificar sin mezclar con categorías.",
    fields: ["Nombre, color."],
    editable: "Alta y edición de etiquetas. Se asignan en la ficha del producto.",
    notEditable: "No reemplazan categoría ni familia.",
    config: "No.",
    tips: ["Útiles para campañas o «destacados»."],
  },
  {
    id: "distributors",
    title: "Proveedores",
    match: (p) => p.startsWith("/admin/distributors"),
    simple: "Quién vende el producto a Soundtec.",
    purpose: "Importaciones, márgenes y filtros de catálogo.",
    fields: ["Nombre."],
    editable: "Alta y nombre.",
    notEditable: "No es el cliente final.",
    config: "Márgenes pueden ser por proveedor.",
    tips: ["Al importar Excel elegís marca + proveedor."],
  },
  {
    id: "categories",
    title: "Categorías",
    match: (p) => p.startsWith("/admin/categories"),
    simple: "Árbol de categorías del catálogo y del portal.",
    purpose: "Navegar y filtrar. La IA puede sugerir asignación.",
    fields: ["Nombre, padre, orden."],
    editable: "Alta, rename, jerarquía.",
    notEditable: "Mover miles de productos se hace en importación o ficha.",
    config: "Visibilidad puede depender de categoría.",
    tips: ["No uses categoría para «marca»: eso va en Marcas."],
  },
  {
    id: "families",
    title: "Familias",
    match: (p) => p.startsWith("/admin/families"),
    simple: "Familias de producto (línea comercial).",
    purpose: "Agrupar más fino que la categoría (ej. DSP, micrófonos de mesa).",
    fields: ["Nombre."],
    editable: "Alta y nombre. Se asignan en la ficha o por IA.",
    notEditable: "No reemplazan categoría.",
    config: "Márgenes pueden ser por familia.",
    tips: ["Sirve para márgenes y para el copiloto de COT."],
  },
  {
    id: "imports",
    title: "Importaciones Excel",
    match: (p) => p === "/admin/imports",
    simple: "Subir lista del proveedor, mapear columnas y normalizar al catálogo.",
    purpose: "Actualizar costos, SKUs y altas sin cargar a mano.",
    fields: [
      "Nombre de la lista, marca, proveedor, archivo.",
      "Estados: pendiente, mapeo, revisión, aplicada.",
    ],
    editable: "Nueva importación y abrir el lote.",
    notEditable: "No pisa a ciegas: hay que mapear y revisar.",
    config: "Mapeos guardados en Admin → Mapeos.",
    tips: ["La IA sugiere el mapeo de columnas si hay clave OpenAI."],
  },
  {
    id: "import-detail",
    title: "Lote de importación",
    match: (p) => /^\/admin\/imports\/[^/]+$/.test(p),
    simple: "Mapear columnas, revisar filas y aplicar al catálogo.",
    purpose: "Confirmar qué campo canónico es cada columna y qué filas entran.",
    fields: ["Mapeo (sku, nombre, costo, etc.), revisión de filas, aplicar."],
    editable: "Mapeo y qué se aplica. Se puede corregir antes de confirmar.",
    notEditable: "El Excel original no se reescribe.",
    config: "Campos canónicos fijos del sistema.",
    tips: ["Revisá costos y SKU proveedor antes de aplicar."],
  },
  {
    id: "crestron-sync",
    title: "Sync Crestron",
    match: (p) => p.startsWith("/admin/crestron-sync") || p.startsWith("/admin/crestron-home"),
    simple: "Bajar / traducir catálogo Crestron y marcar compatibles Home.",
    purpose: "Mantener SKUs y nombres Crestron al día.",
    fields: ["Sync, traducción de categorías, compatibles Home."],
    editable: "Disparar sync y marcar compatibilidad.",
    notEditable: "El catálogo oficial de Crestron no se edita acá.",
    config: "Claves en Settings → Integraciones si aplica.",
    tips: ["La pestaña Crestron Home también está en Productos."],
  },
  {
    id: "sonance",
    title: "Importar Sonance/BLAZE",
    match: (p) => p.startsWith("/admin/sonance-import"),
    simple: "Importador específico de esas marcas, con traducción.",
    purpose: "No usar el Excel genérico si hay flujo propio.",
    fields: ["Archivo, traducción de categorías."],
    editable: "Subir y confirmar.",
    notEditable: "El listado del fabricante.",
    config: "OpenAI para traducir si está la clave.",
    tips: ["Revisá nombres en español después de traducir."],
  },
  {
    id: "share-lists",
    title: "Listas compartibles",
    match: (p) => p.startsWith("/admin/share-lists"),
    simple: "Link público de una lista filtrada, con precios de un cliente.",
    purpose: "Mandar un recorte del catálogo sin dar acceso al portal.",
    fields: ["Nombre, filtros, cliente de precios, opciones del link."],
    editable: "Alta, filtros y desactivar el link.",
    notEditable: "El visitante no ve costos ni el admin.",
    config: "Los precios salen del cliente elegido (márgenes/descuentos).",
    tips: ["Si el link muestra mal el precio, revisá el cliente asignado."],
  },
  {
    id: "mappings",
    title: "Mapeos",
    match: (p) => p.startsWith("/admin/mappings"),
    simple: "Mapeos de columnas reutilizables para importar Excel.",
    purpose: "No volver a mapear el mismo formato del proveedor.",
    fields: ["Origen → campo canónico."],
    editable: "Guardar y reutilizar en la próxima importación.",
    notEditable: "Los campos canónicos del sistema.",
    config: "Se usan desde Importaciones.",
    tips: ["Si el proveedor cambió el encabezado, rehacé el mapeo."],
  },
  {
    id: "scrapers",
    title: "Scrapers",
    match: (p) => p.startsWith("/admin/scrapers"),
    simple: "Jobs para bajar datos de sitios de marca (uso interno).",
    purpose: "Apoyar altas cuando no hay Excel.",
    fields: ["Estado del job, disparar."],
    editable: "Correr el scraper si tenés permiso.",
    notEditable: "No reemplaza una importación revisada.",
    config: "Permiso scrapers.manage.",
    tips: ["Siempre revisá el resultado en el catálogo."],
  },
  {
    id: "ncm",
    title: "Posiciones NCM",
    match: (p) => p.startsWith("/admin/ncm"),
    simple: "Arancel / posición arancelaria de los productos.",
    purpose: "El precio de venta puede incluir el arancel de nacionalización.",
    fields: ["Posición, % arancel, sugerencia IA."],
    editable: "Asignar posición al producto. Settings de coeficiente en Precios.",
    notEditable: "La nomenclatura oficial no se inventa.",
    config: "Settings → Precios y moneda (coeficiente de nacionalización).",
    tips: ["Sin NCM el cálculo puede quedar corto en productos importados."],
  },
  {
    id: "margins",
    title: "Márgenes",
    match: (p) => p.startsWith("/admin/margins"),
    simple: "Reglas de margen sobre el costo (global, marca, familia, etc.). Podés aplicar la misma a varias marcas o clientes.",
    purpose: "Armar el precio de lista. Gana la regla más específica.",
    fields: ["A quién aplica, sobre qué, markup o margen %, fecha de alta."],
    editable: "Alta y edición de cada regla. El timestamp de creación (y de edición, si hubo cambios) queda a la vista.",
    notEditable: "No es un descuento al cliente. El PVP no se tipea en el producto.",
    config: "Margen global también en Settings → Precios.",
    tips: ["Un margen de producto pisa el de marca."],
  },
  {
    id: "discounts",
    title: "Descuentos",
    match: (p) => p.startsWith("/admin/discounts"),
    simple: "Descuentos comerciales. Podés aplicar el mismo % a varias marcas, familias o clientes.",
    purpose: "Bajar el precio que ve un cliente o una lista. Si el catálogo muestra un % y esta pantalla parece vacía, mirá los descuentos de ficha y las etiquetas del fabricante.",
    fields: ["Reglas (alcance, porcentaje, fecha de alta).", "Descuentos en ficha de producto.", "Etiquetas de oferta del fabricante."],
    editable: "Alta y edición de reglas. Quitar descuentos de ficha y etiquetas de oferta copiadas del proveedor.",
    notEditable: "No cambia el costo. El cliente ve el neto calculado. Las etiquetas del fabricante no son un descuento Soundtec.",
    config: "Se combina con márgenes y visibilidad.",
    tips: ["El admin, en una solicitud, ve el mismo precio que el cliente."],
  },
  {
    id: "visibility",
    title: "Visibilidad por cliente",
    match: (p) => p.startsWith("/admin/visibility"),
    simple: "Qué marcas/categorías/productos ve cada cliente en el portal.",
    purpose: "No mostrar todo el catálogo a todos.",
    fields: ["Cliente, inclusiones/exclusiones, fecha de alta."],
    editable: "Alta y edición de reglas por cliente (ocultar o permitir).",
    notEditable: "El catálogo interno sigue existiendo; sólo se oculta en el portal.",
    config: "Visibilidad por defecto en Settings → General.",
    tips: ["Si un cliente «no ve un producto», mirá acá antes de tocar el producto."],
  },
  {
    id: "clients",
    title: "Clientes",
    match: (p) => p === "/admin/clients",
    simple: "Empresas: razón social, lista de precios, visibilidad, cuenta.",
    purpose: "El cliente comercial de las COT y del portal.",
    fields: ["Razón social, nombre de fantasía, lista de precios, activo."],
    editable: "Alta y ficha. Los usuarios de portal se vinculan en Usuarios.",
    notEditable: "No es el usuario de login: eso es Usuarios.",
    config: "Listas de precios / descuentos / visibilidad.",
    tips: ["Sin cliente en una COT no se puede emitir."],
  },
  {
    id: "client-detail",
    title: "Ficha de cliente",
    match: (p) => /^\/admin\/clients\/[^/]+$/.test(p),
    simple: "Datos comerciales, usuarios vinculados, historial.",
    purpose: "Ajustar precios y quién entra al portal de esa empresa.",
    fields: ["Empresa, lista, usuarios, solicitudes."],
    editable: "Datos comerciales. Usuarios se gestionan en Usuarios.",
    notEditable: "Las COT emitidas de ese cliente no se reescriben acá.",
    config: "Visibilidad y descuentos de este cliente.",
    tips: ["En Emitir de una COT podés reusar las condiciones que este cliente usó antes."],
  },
  {
    id: "users",
    title: "Usuarios",
    match: (p) => p === "/admin/users",
    simple: "Logins: admin, empleados y clientes de portal.",
    purpose: "Quién entra y con qué rol / permisos.",
    fields: ["Nombre, email, rol, cliente comercial, activo."],
    editable: "Alta y ficha si tenés users.manage.",
    notEditable: "No cambies el rol de un SUPER_ADMIN a la ligera.",
    config: "Roles y permisos en Settings → Roles.",
    tips: ["Un empleado de catálogo puede ser CLIENT + rol custom con scopes de admin."],
  },
  {
    id: "user-detail",
    title: "Ficha de usuario",
    match: (p) => /^\/admin\/users\/[^/]+$/.test(p),
    simple: "Rol, cliente, firma de COT, activo.",
    purpose: "Vincular el login a una empresa y a un rol custom.",
    fields: ["Rol base, rol custom, cliente, firma (nombre/cargo) para COT."],
    editable: "Esos campos. La contraseña se resetea según el flujo de auth.",
    notEditable: "Los tickets y COT que ya creó.",
    config: "Settings → Roles.",
    tips: ["La firma de la COT se puede guardar acá y se copia al emitir."],
  },
  {
    id: "landing",
    title: "Landing pública",
    match: (p) => p.startsWith("/admin/landing"),
    simple: "Textos e imágenes de la home para quien no está logueado.",
    purpose: "Marca pública, no el portal de clientes.",
    fields: ["Bloques de contenido de la landing."],
    editable: "Copy e imágenes de la landing.",
    notEditable: "El catálogo logueado. Logo/colores globales van en Branding.",
    config: "Settings → Marca y apariencia.",
    tips: ["No pongas precios de lista acá."],
  },
  {
    id: "settings",
    title: "Configuración",
    match: (p) => p === "/admin/settings",
    simple: "Hub: general, marca, precios, COT, IA, claves, roles.",
    purpose: "Todo lo que no es operación diaria.",
    fields: ["Tarjetas por sección, filtradas por tu permiso."],
    editable: "Entrar a cada sección.",
    notEditable: "Las secciones que no ves son por permiso, no están rotas.",
    config: "Este es el config.",
    tips: ["Cotizaciones tiene plantilla, clasificadores y borradores de módulos."],
  },
  {
    id: "settings-general",
    title: "Settings · General",
    match: (p) => p.startsWith("/admin/settings/general"),
    simple: "Nombre del portal, moneda y visibilidad por defecto del catálogo.",
    purpose: "Defaults de toda la plataforma.",
    fields: ["Nombre, moneda base, visibilidad default."],
    editable: "Esos settings. Guardar por campo.",
    notEditable: "No cambia COT ya emitidas.",
    config: "Acá.",
    tips: ["La visibilidad fina por cliente está en Visibilidad."],
  },
  {
    id: "settings-branding",
    title: "Settings · Marca",
    match: (p) => p.startsWith("/admin/settings/branding"),
    simple: "Logo y colores del admin/portal.",
    purpose: "Identidad de la plataforma (no la plantilla Word de COT).",
    fields: ["Logo URL, colores."],
    editable: "Branding de la app.",
    notEditable: "Logo/marcas/ISO del PDF de COT se configuran en Settings → Cotizaciones.",
    config: "Acá vs Cotizaciones (documento).",
    tips: ["Son dos logos distintos: el del menú y el del presupuesto."],
  },
  {
    id: "settings-pricing",
    title: "Settings · Precios",
    match: (p) => p.startsWith("/admin/settings/pricing"),
    simple: "Margen global, tipo de cambio de venta, coeficiente de nacionalización.",
    purpose: "Números que entran en todos los precios.",
    fields: ["Margen global %, FX, coeficiente NCM."],
    editable: "Esos valores. Las reglas finas están en Márgenes y Descuentos.",
    notEditable: "No reescribe COT emitidas.",
    config: "Acá + Márgenes + Descuentos + NCM.",
    tips: ["El ticker de dólar del menú es informativo; el FX de venta es este."],
  },
  {
    id: "settings-quotes",
    title: "Settings · Cotizaciones",
    match: (p) => p === "/admin/settings/quotes",
    simple: "Numeración, identidad del PDF, condiciones default, atajos a plantilla/clasificadores/módulos.",
    purpose: "Cómo nacen las COT nuevas.",
    fields: [
      "Prefijo, fecha, separador, dígitos, siguiente número.",
      "Layout, perfil, IVA, entrega.",
      "Vigencia, pago, garantía.",
      "Tagline, dirección, tel, mail, web, rutas de logo/marcas/ISO.",
    ],
    editable: "Defaults de COT NUEVAS. Plantilla visual = textos fijos de las nuevas.",
    notEditable: "Las COT ya creadas no se reescriben al cambiar la maestra.",
    config: "Subpáginas: plantilla, clasificadores, módulos.",
    tips: ["Cuidado con «siguiente número»: puede duplicar."],
  },
  {
    id: "settings-quotes-plantilla",
    title: "Plantilla visual de COT",
    match: (p) => p.startsWith("/admin/settings/quotes/plantilla"),
    simple: "Presupuesto de muestra: clickeá el texto fijo y editá la maestra.",
    purpose: "Presentación, marcas, ISO, condiciones, cierre de las COT nuevas.",
    fields: ["Módulos fijos sobre el documento de muestra."],
    editable: "La maestra. Aplica a altas nuevas.",
    notEditable: "No pisa COT existentes. Generar propuesta nunca reescribe estos bloques.",
    config: "Anchos de marcas/ISO en settings de COT.",
    tips: ["En una COT ya creada podés retocar a mano ese texto; no cambia la maestra."],
  },
  {
    id: "settings-classifiers",
    title: "Clasificadores de COT",
    match: (p) => p.startsWith("/admin/settings/quotes/clasificadores"),
    simple: "Tipo de sala, escala y selectores internos del inicio de cada COT.",
    purpose: "Memoria: sugerir equipos de COT parecidas.",
    fields: ["Nombre del clasificador, ayuda, opciones. Archivar."],
    editable: "Opciones y nuevos clasificadores.",
    notEditable: "El cliente no los ve. Archivar no borra COT viejas.",
    config: "Acá.",
    tips: ["Videoconferencia grande = misma base que mediana + extras: eso lo usa la IA."],
  },
  {
    id: "settings-modules",
    title: "Borradores de módulos",
    match: (p) => p.startsWith("/admin/settings/quotes/modulos"),
    simple: "Módulos extra reutilizables (título, texto, fotos). No entran solos.",
    purpose: "Insertarlos a pedido desde Agregar módulo en una COT.",
    fields: ["Lista de borradores, archivar."],
    editable: "Se crean desde una COT (guardar como borrador).",
    notEditable: "No se agregan por defecto a cada presupuesto nuevo.",
    config: "Acá se listan; el alta vive en el editor de COT.",
    tips: ["Layout de fotos: izq/der/arriba/abajo/dos en fila."],
  },
  {
    id: "settings-ai",
    title: "Settings · Prompts y modelos",
    match: (p) => p.startsWith("/admin/settings/ai"),
    simple: "Qué modelo y prompt usa cada función de IA.",
    purpose: "Descripciones, mapeo de Excel, propuesta de COT, este chatbot de ayuda.",
    fields: ["Modelo global, prompts por función."],
    editable: "Prompts y modelo. Hace falta la API key en Integraciones.",
    notEditable: "No cambia textos ya guardados en productos o COT.",
    config: "Clave en Settings → Integraciones (openai.api_key).",
    tips: ["Si el chatbot no «piensa», falta la clave o el modelo."],
  },
  {
    id: "settings-integrations",
    title: "Settings · Integraciones",
    match: (p) => p.startsWith("/admin/settings/integrations"),
    simple: "API keys: OpenAI, Serper, imágenes.",
    purpose: "Sin OpenAI no hay propuesta, descripciones ni chatbot de ayuda con IA.",
    fields: ["openai.api_key, modelo, serper, provider de imágenes."],
    editable: "Las claves. Se guardan en DB (no hace falta redeploy).",
    notEditable: "No las pegues en una COT.",
    config: "Acá.",
    tips: ["Serper = buscar fotos. OpenAI = textos e imágenes DALL·E si está activo."],
  },
  {
    id: "settings-roles",
    title: "Settings · Roles",
    match: (p) => p.startsWith("/admin/settings/roles"),
    simple: "Permisos por rol custom: qué pantallas ve cada empleado.",
    purpose: "Un vendedor no es lo mismo que catálogo o super admin.",
    fields: ["Scopes: productos, COT, precios, tickets, etc. hidePrices."],
    editable: "Checkboxes del rol. Se asigna el rol en la ficha de usuario.",
    notEditable: "SUPER_ADMIN siempre tiene full access.",
    config: "Acá + Usuarios.",
    tips: ["Si no ves Ayuda no es por rol: Ayuda está para todo el admin. Si no ves una pantalla, es el scope."],
  },
  {
    id: "changelog",
    title: "Changelog",
    match: (p) => p.startsWith("/admin/changelog"),
    simple: "Novedades del panel admin. Solo lectura: cada push las publica; el popup aparece por usuario hasta Entendido.",
    purpose: "Avisar cambios de la plataforma al equipo interno, no a los clientes.",
    fields: ["Las entradas viven en el código. Versión, En pocas palabras, NUEVO / FIX / MEJORA."],
    editable: "Nada. No se puede cargar, editar ni borrar a mano.",
    notEditable: "Todo el historial. Tampoco aparece en el portal del cliente.",
    config: "El botón está arriba del dólar, en el menú izquierdo.",
    tips: ["Las del mismo día se ven juntas. Cada push nuevo abre el popup a quien no lo leyó."],
  },
  {
    id: "tickets",
    title: "Tickets al dev",
    match: (p) => p.startsWith("/admin/tickets"),
    simple: "Reportes técnicos. Los del chatbot llegan con prefijo [Ayuda] y la URL.",
    purpose: "El desarrollador ve fallas y pedidos.",
    fields: ["Título, prioridad, descripción, estado, resolución."],
    editable: "Crear (admin). Cambiar estado/resolución. Cualquier staff puede crear desde el chatbot.",
    notEditable: "No borra datos de COT.",
    config: "Permiso tickets.manage para ver la lista.",
    tips: ["Desde el chatbot: «esto no funciona» arma el ticket con la pantalla."],
  },
  {
    id: "ayuda",
    title: "Ayuda y tutorial",
    match: (p) => p.startsWith("/admin/ayuda"),
    simple: "Documentación simple y detallada. El chatbot de abajo a la derecha la usa para responder.",
    purpose: "Enseñar la plataforma y reportar errores.",
    fields: ["Tabs Simple / Detallado, índice, recorridos."],
    editable: "Sólo lectura. El contenido lo mantiene el desarrollo.",
    notEditable: "No cambia settings.",
    config: "El botón Ayuda está en todo el admin.",
    tips: ["Preguntale al chatbot «qué hace esta pantalla» o pedile un ticket."],
  },
];

export function moduleForPath(pathname: string): HelpModule {
  return HELP_MODULES.find((mod) => mod.match(pathname)) || HELP_MODULES[0];
}
